### ISSUE TITLE
"TypeError: Assignment to constant variable" when testing some URLs

### ISSUE THREAD

**Issue by malcomio** [squizlabs/HTML_CodeSniffer#321]
## Steps to reproduce

1. install the bookmarklet
2. visit one of the following URLs: 
    1. https://www.transizionedigitale.it/
    2.  https://www.neso.energy/
5. click the bookmarklet

## Expected result

The sniffer should run and report any issues

## Actual result

The test does not complete
Errors in console:

```
Uncaught TypeError: Assignment to constant variable.
    at Object.testNullAltText (HTMLCS.js:24:223570)
    at Object.addNullAltTextResults (HTMLCS.js:24:222007)
    at Object.process (HTMLCS.js:24:221802)
    at m (HTMLCS.js:24:288483)
    at c (HTMLCS.js:24:288090)
    at Object.run (HTMLCS.js:24:287448)
    at HTMLCS.js:24:286284
    at HTMLCS.js:24:286545
    at h (HTMLCS.js:24:289153)
    at HTMLCS.js:24:289131
```

Originally raised as https://github.com/pa11y/pa11y/issues/709

**Comment by malcomio** [comment]
Using a debug version, the output is as follows:

```
HTMLCS.js:2758  Uncaught TypeError: Assignment to constant variable.
    at Object.testNullAltText (HTMLCS.js:2758:18)
    at Object.addNullAltTextResults (HTMLCS.js:2711:27)
    at Object.process (HTMLCS.js:2698:18)
    at _processSniffs (HTMLCS.js:5414:23)
    at _run (HTMLCS.js:5387:17)
    at Object.run (HTMLCS.js:5338:13)
    at HTMLCS.js:5259:24
    at HTMLCS.js:5282:22
    at _registerSniffs (HTMLCS.js:5465:22)
    at HTMLCS.js:5470:13
```

**Comment by GRASPARK** [comment]
@malcomio 

I have checked both links and confirmed the following:

- https://www.transizionedigitale.it/ - HTML_Code_Sniffing-Tool is working
- https://www.neso.energy/ - HTML_Code_Sniffing-Tool is not working

It appears that the issue with the second link is related to the presence of a Content Security Policy (CSP), which is preventing the code-sniffing method from functioning correctly.

For your reference, CSP is enabled on the second link but not on the first.

If you need any more details than please share me screenshot to help you with.

**Comment by malcomio** [comment]
thanks @GRASPARK that makes sense - the problem seems to be addressed by the changes in #322
